plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":domain:location-login"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    add("ksp", libs.hilt.compiler.androidx)
    add("ksp", libs.hilt.compiler)
    add("ksp", libs.kotlin.jvm.metadata)
    add("kspTest", libs.hilt.compiler)
    add("kspAndroidTest", libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    testImplementation(project(":domain:location-login"))
    testImplementation(project(":feature:file-contact"))
    testImplementation(project(":core:media"))
    testImplementation(project(":core:cart"))
    testImplementation(project(":core:note"))
    testImplementation(project(":core:login"))
    testImplementation(project(":core:timer"))
    testImplementation(project(":core:message"))
    testImplementation(project(":core:account"))
    testImplementation(project(":core:contact"))
    testImplementation(project(":core:gallery"))
    testImplementation(project(":core:session"))
    testImplementation(project(":core:notification"))
    testImplementation(project(":core:group"))
    testImplementation(project(":core:feed"))
    testImplementation(project(":core:event"))
    testImplementation(project(":core:push"))
    testImplementation(project(":core:location"))
    testImplementation(project(":core:profile"))
    testImplementation(project(":core:calendar"))
    testImplementation(project(":core:checkout"))
    testImplementation(project(":core:alarm"))
    testImplementation(project(":feature:identity-contact"))
    testImplementation(project(":core:list"))
    testImplementation(project(":core:article"))
    testImplementation(project(":core:analytics"))
    testImplementation(project(":core:post"))
    testImplementation(project(":core:map"))
    testImplementation(project(":core:weather"))
    testImplementation(project(":core:sync"))
    testImplementation(project(":core:news"))
    testImplementation(project(":core:log"))
    testImplementation(project(":core:file"))
    testImplementation(project(":core:photo"))
    testImplementation(project(":core:todo"))
    testImplementation(project(":core:task"))
    testImplementation(project(":core:share"))
    testImplementation(project(":core:report"))
    testImplementation(project(":core:status"))
    testImplementation(project(":core:document"))

}