plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":core:login"))
    implementation(project(":core:video"))
    implementation(project(":core:audio"))
    implementation(project(":core:weather"))
    implementation(project(":core:user"))
    implementation(project(":core:status"))
    implementation(project(":core:network"))
    implementation(project(":core:list"))
    implementation(project(":core:task"))
    implementation(project(":core:search"))
    implementation(project(":core:document"))
    implementation(project(":core:sync"))
    implementation(project(":core:todo"))
    implementation(project(":core:alarm"))
    implementation(project(":core:comment"))
    implementation(project(":core:timer"))
    implementation(project(":core:map"))
    implementation(project(":core:feed"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    add("ksp", libs.hilt.compiler.androidx)
    add("ksp", libs.hilt.compiler)
    add("ksp", libs.kotlin.jvm.metadata)
    add("kspTest", libs.hilt.compiler)
    add("kspAndroidTest", libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    testImplementation(project(":core:login"))
    testImplementation(project(":core:video"))
    testImplementation(project(":core:audio"))
    testImplementation(project(":core:weather"))
    testImplementation(project(":core:user"))
    testImplementation(project(":core:status"))
    testImplementation(project(":core:network"))
    testImplementation(project(":core:list"))
    testImplementation(project(":core:task"))
    testImplementation(project(":core:search"))
    testImplementation(project(":core:document"))
    testImplementation(project(":core:sync"))
    testImplementation(project(":core:todo"))
    testImplementation(project(":core:alarm"))
    testImplementation(project(":core:comment"))
    testImplementation(project(":core:timer"))
    testImplementation(project(":core:map"))
    testImplementation(project(":core:feed"))

}