plugins {
    id("awesome.androidlib.plugin")
}

dependencies {
    implementation(project(":core:map"))
    implementation(project(":core:log"))
    implementation(project(":core:calendar"))
    implementation(project(":core:notification"))
    implementation(project(":core:comment"))
    implementation(project(":core:article"))
    implementation(project(":core:identity"))
    implementation(project(":core:account"))
    implementation(project(":core:weather"))
    implementation(project(":core:feed"))
    implementation(project(":core:task"))
    implementation(project(":core:user"))
    implementation(project(":core:cart"))
    implementation(project(":core:event"))
    implementation(project(":core:todo"))
    implementation(project(":core:login"))
    implementation(project(":core:setting"))
    implementation(project(":core:timer"))
    implementation(project(":core:status"))
    implementation(project(":core:share"))
    implementation(project(":core:contact"))
    implementation(project(":core:podcast"))
    implementation(project(":core:media"))
    implementation(project(":core:metric"))
    implementation(project(":core:forecast"))
    implementation(project(":core:note"))
    implementation(project(":core:network"))
    implementation(project(":core:push"))
    implementation(project(":core:news"))
    implementation(project(":core:session"))
    implementation(project(":core:video"))
    implementation(project(":core:gallery"))
    implementation(project(":core:checkout"))
    implementation(project(":core:message"))
    implementation(project(":core:report"))
    implementation(libs.androidx.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.lifecycle.viewmodel.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.livedata.ktx)
    implementation(libs.lifecycle.common.java8)
    implementation(libs.coroutines.android)
    implementation(libs.fragment.ktx)
    implementation(libs.activity.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.work.runtime.ktx)
    
    implementation(libs.hilt.work)
    implementation(libs.hilt.android)
    
    add("ksp", libs.hilt.compiler.androidx)
    add("ksp", libs.hilt.compiler)
    add("ksp", libs.kotlin.jvm.metadata)
    add("kspTest", libs.hilt.compiler)
    add("kspAndroidTest", libs.hilt.compiler)
    testImplementation(libs.hilt.android.testing)
    
    
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.runtime)
    implementation(libs.compose.runtime.livedata)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    debugImplementation(libs.compose.ui.tooling)
    debugImplementation(libs.compose.ui.test.manifest)
    
    testImplementation(libs.junit4)
    testImplementation(libs.junit5.vintage)
    testImplementation(libs.coroutines.test)
    testImplementation(libs.core.testing)
    testImplementation(libs.mockk)
    testImplementation(libs.truth)
    testImplementation(libs.kotlin.test)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.work.testing)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.espresso.core)
    testImplementation(project(":core:map"))
    testImplementation(project(":core:log"))
    testImplementation(project(":core:calendar"))
    testImplementation(project(":core:notification"))
    testImplementation(project(":core:comment"))
    testImplementation(project(":core:article"))
    testImplementation(project(":core:identity"))
    testImplementation(project(":core:account"))
    testImplementation(project(":core:weather"))
    testImplementation(project(":core:feed"))
    testImplementation(project(":core:task"))
    testImplementation(project(":core:user"))
    testImplementation(project(":core:cart"))
    testImplementation(project(":core:event"))
    testImplementation(project(":core:todo"))
    testImplementation(project(":core:login"))
    testImplementation(project(":core:setting"))
    testImplementation(project(":core:timer"))
    testImplementation(project(":core:status"))
    testImplementation(project(":core:share"))
    testImplementation(project(":core:contact"))
    testImplementation(project(":core:podcast"))
    testImplementation(project(":core:media"))
    testImplementation(project(":core:metric"))
    testImplementation(project(":core:forecast"))
    testImplementation(project(":core:note"))
    testImplementation(project(":core:network"))
    testImplementation(project(":core:push"))
    testImplementation(project(":core:news"))
    testImplementation(project(":core:session"))
    testImplementation(project(":core:video"))
    testImplementation(project(":core:gallery"))
    testImplementation(project(":core:checkout"))
    testImplementation(project(":core:message"))
    testImplementation(project(":core:report"))

}